
export const spells = [
    { name: "Magic Arrow", rate: 10, power: [10, 20, 30], type:"air"},
    { name: "Fire Wall", rate: 10, power: [10, 20, 30], type:"fire"},
    { name: "Fire Ball", rate: 10, power: [15, 30, 60], type:"fire"},
    { name: "Land Mine", rate: 10, power: [25, 50, 100], type:"fire"},
    { name: "Armageddon", rate: 50, power: [30, 60, 120], type:"fire"},
    { name: "Inferno", rate: 10, power: [25, 50, 80], type:"fire"},
    { name: "Lightning Bolt", rate: 25, power: [10, 20, 30], type:"air" },
    { name: "Chain Lightning", rate: 40, power: [25, 50, 100], type:"air"},
    { name: "Ice Bolt", rate: 20, power: [10, 20, 30], type:"water" },
    { name: "Frost Ring", rate: 10, power: [15, 30, 60], type:"water"},
    { name: "Death Ripple", rate: 5, power: [10, 20, 30], type:"earth"},
    { name: "Meteor Shower", rate: 25, power: [25, 50, 100], type:"earth"},
    { name: "Implosion", rate: 75, power: [100, 200, 300], type:"earth"},
    {name:"Sumon Air Elemental", power: [2, 3, 4], type:"air"},
    {name:"Summon Earth Elemental", power: [2, 3, 4], type:"earth"},
    {name:"Summon Fire Elemental", power: [2, 3, 4], type:"fire"},
    {name:"summon Water Elemental", power: [2, 3, 4], type:"water"},
  ];
  export const creatures = [
    { name: "Pikeman", attack:4, defense:5, mindmg:1, maxdmg:3, health:10, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pikeman_Animation.gif"},
    { name: "Halberdier", attack:6, defense:5, mindmg:2, maxdmg:3, health:10, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Halberdier_Animation.gif"}, 
    { name: "Archer", attack:6, defense:3, mindmg:2, maxdmg:3, health:10, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Archer_Animation.gif" },
    { name: "Marksman", attack:6, defense:5, mindmg:2, maxdmg:3, health:10, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Marksman_Animation.gif" },
    { name: "Griffin", attack:8, defense:8, mindmg:3, maxdmg:6, health:25, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Griffin_Animation.gif" },
    { name: "Royal_Griffin", attack:9, defense:9, mindmg:3, maxdmg:6, health:25, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Royal_Griffin_Animation.gif" },
    { name: "Swordsman", attack:10, defense:12, mindmg:6, maxdmg:9, health:35, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Swordsman_Animation.gif" },
    { name: "Crusader", attack:12, defense:12, mindmg:7, maxdmg:10, health:35, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Crusader_Animation.gif" },
    { name: "Monk", attack:12, defense:7, mindmg:10, maxdmg:12, health:30, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Monk_Animation.gif" },
    { name: "Zealot", attack:12, defense:10, mindmg:10, maxdmg:12, health:30, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Zealot_Animation.gif" },
    { name: "Cavalier", attack:15, defense:15, mindmg:15, maxdmg:25, health:100, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Cavalier_Animation.gif" },
    { name: "Champion", attack:16, defense:16, mindmg:20, maxdmg:25, health:100, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Champion_Animation.gif" },
    { name: "Angel", attack:20, defense:20, mindmg:50, maxdmg:50, health:200, speed:12, type: "Hate Devil", imgUrl:"css/img/creatures_animation/Creature_Angel_Animation.gif" },
    { name: "Archangel", attack:30, defense:30, mindmg:50, maxdmg:50, health:250, speed:18, type: "Hate Devil", imgUrl:"css/img/creatures_animation/Creature_Archangel_Animation.gif" },

    { name: "Centaur", attack:5, defense:3, mindmg:2, maxdmg:3, health:8, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Centaur_Animation.gif" },
    { name: "Centaur_Captain", attack:6, defense:3, mindmg:2, maxdmg:3, health:10, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Centaur_Captain_Animation.gif" },
    { name: "Dwarf", attack:6, defense:7, mindmg:2, maxdmg:4, health:20, speed:3, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Dwarf_Animation.gif" },
    { name: "Battle_Dwarf", attack:7, defense:7, mindmg:2, maxdmg:4, health:20, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Battle_Dwarf_Animation.gif" },
    { name: "Wood_Elf", attack:9, defense:5, mindmg:3, maxdmg:5, health:15, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wood_Elf_Animation.gif" },
    { name: "Grand_Elf", attack:9, defense:5, mindmg:3, maxdmg:5, health:15, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Grand_Elf_Animation.gif" },
    { name: "Pegasus", attack:9, defense:8, mindmg:5, maxdmg:9, health:30, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pegasus_Animation.gif" },
    { name: "Silver_Pegasus", attack:9, defense:10, mindmg:5, maxdmg:9, health:30, speed:12, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Silver_Pegasus_Animation.gif" },
    { name: "Dendroid_Guard", attack:9, defense:12, mindmg:10, maxdmg:14, health:55, speed:3, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Dendroid_Guard_Animation.gif" },
    { name: "Dendroid_Soldier", attack:9, defense:12, mindmg:10, maxdmg:14, health:65, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Dendroid_Soldier_Animation.gif" },
    { name: "Unicorn", attack:15, defense:14, mindmg:18, maxdmg:22, health:90, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Unicorn_Animation.gif" },
    { name: "War_Unicorn", attack:15, defense:14, mindmg:18, maxdmg:22, health:110, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_War_Unicorn_Animation.gif" },
    { name: "Green_Dragon", attack:18, defense:18, mindmg:40, maxdmg:50, health:180, speed:10, type: "lower dragon", imgUrl:"css/img/creatures_animation/Creature_Green_Dragon_Animation.gif" },
    { name: "Gold_Dragon", attack:27, defense:27, mindmg:40, maxdmg:50, health:250, speed:16, type: "mediom dragon", imgUrl:"css/img/creatures_animation/Creature_Gold_Dragon_Animation.gif" },

    { name: "Gremlin", attack:3, defense:3, mindmg:1, maxdmg:2, health:4, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Gremlin_Animation.gif" },
    { name: "Master_Gremlin", attack:4, defense:4, mindmg:1, maxdmg:2, health:4, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Master_Gremlin_Animation.gif" },
    { name: "Stone_Gargoyle", attack:6, defense:6, mindmg:2, maxdmg:3, health:16, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Stone_Gargoyle_Animation.gif" },
    { name: "Obsidian_Gargoyle", attack:7, defense:7, mindmg:2, maxdmg:3, health:16, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Obsidian_Gargoyle_Animation.gif" },
    { name: "Stone_Golem", attack:7, defense:10, mindmg:4, maxdmg:5, health:30, speed:3, type: "Stone Golem", imgUrl:"css/img/creatures_animation/Creature_Stone_Golem_Animation.gif" },
    { name: "Iron_Golem", attack:9, defense:10, mindmg:4, maxdmg:5, health:35, speed:5, type: "Iron Golem", imgUrl:"css/img/creatures_animation/Creature_Iron_Golem_Animation.gif" },
    { name: "Mage", attack:11, defense:8, mindmg:7, maxdmg:9, health:25, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Mage_Animation.gif" },
    { name: "Arch_Mage", attack:12, defense:9, mindmg:7, maxdmg:9, health:30, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Arch_Mage_Animation.gif" },
    { name: "Genie", attack:12, defense:12, mindmg:13, maxdmg:16, health:40, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Genie_Animation.gif" },
    { name: "Master_Genie", attack:12, defense:12, mindmg:13, maxdmg:16, health:40, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Master_Genie_Animation.gif" },
    { name: "Naga", attack:16, defense:13, mindmg:20, maxdmg:20, health:110, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Naga_Animation.gif" },
    { name: "Naga_Queen", attack:16, defense:13, mindmg:30, maxdmg:30, health:110, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Naga_Queen_Animation.gif" },
    { name: "Giant", attack:19, defense:16, mindmg:40, maxdmg:60, health:150, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Giant_Animation.gif" },
    { name: "Titan", attack:24, defense:24, mindmg:40, maxdmg:60, health:300, speed:11, type: "Hate Black Dragon", imgUrl:"css/img/creatures_animation/Creature_Titan_Animation.gif" },

    { name: "Imp", attack:2, defense:3, mindmg:1, maxdmg:2, health:4, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Imp_Animation.gif" },
    { name: "Familiar", attack:4, defense:4, mindmg:1, maxdmg:2, health:4, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Familiar_Animation.gif" },
    { name: "Gog", attack:6, defense:4, mindmg:2, maxdmg:4, health:13, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Gog_Animation.gif" },
    { name: "Magog", attack:7, defense:4, mindmg:2, maxdmg:4, health:13, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Magog_Animation.gif" },
    { name: "Hell_Hound", attack:10, defense:6, mindmg:2, maxdmg:7, health:25, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Hell_Hound_Animation.gif" },
    { name: "Cerberus", attack:10, defense:8, mindmg:2, maxdmg:7, health:25, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Cerberus_Animation.gif" },
    { name: "Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:35, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Demon_Animation.gif" },
    { name: "Horned_Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:40, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Horned_Demon_Animation.gif" },
    { name: "Pit_Fiend", attack:13, defense:13, mindmg:13, maxdmg:17, health:45, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pit_Fiend_Animation.gif" },
    { name: "Pit_Lord", attack:13, defense:113, mindmg:13, maxdmg:17, health:45, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pit_Lord_Animation.gif" },
    { name: "Efreet", attack:16, defense:12, mindmg:16, maxdmg:24, health:90, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Efreeti_Animation.gif" },
    { name: "Efreet_Sultan", attack:16, defense:14, mindmg:16, maxdmg:24, health:90, speed:13, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Efreet_Sultan_Animation.gif" },
    { name: "Devil", attack:19, defense:21, mindmg:30, maxdmg:40, health:160, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Devil_Animation.gif" },
    { name: "Arch_Devil", attack:26, defense:28, mindmg:30, maxdmg:40, health:200, speed:17, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Arch_Devil_Animation.gif" },

    { name: "Skeleton", attack:5, defense:4, mindmg:1, maxdmg:3, health:6, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Skeleton_Animation.gif" },
    { name: "Skeleton_Warrior", attack:6, defense:6, mindmg:1, maxdmg:3, health:6, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Skeleton_Warrior_Animation.gif" },
    { name: "Walking_Dead", attack:5, defense:5, mindmg:2, maxdmg:3, health:15, speed:3, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Walking_Dead_Animation.gif" },
    { name: "Zombie", attack:5, defense:5, mindmg:2, maxdmg:3, health:20, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Zombie_Animation.gif" },
    { name: "Wight", attack:7, defense:7, mindmg:3, maxdmg:5, health:18, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wight_Animation.gif" },
    { name: "Wraith", attack:7, defense:7, mindmg:3, maxdmg:5, health:18, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wraith_Animation.gif" },
    { name: "Vampire", attack:10, defense:9, mindmg:5, maxdmg:8, health:30, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Vampire_Animation.gif" },
    { name: "Vampire_Lord", attack:10, defense:10, mindmg:5, maxdmg:8, health:40, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Vampire_Lord_Animation.gif" },
    { name: "Lich", attack:13, defense:10, mindmg:11, maxdmg:13, health:30, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Lich_Animation.gif" },
    { name: "Power_Lich", attack:13, defense:10, mindmg:11, maxdmg:15, health:40, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Power_Lich_Animation.gif" },
    { name: "Black_Knight", attack:16, defense:16, mindmg:15, maxdmg:30, health:120, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Black_Knight_Animation.gif" },
    { name: "Dread_Knight", attack:18, defense:18, mindmg:15, maxdmg:30, health:120, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Dread_Knight_Animation.gif" },
    { name: "Bone_Dragon", attack:17, defense:15, mindmg:25, maxdmg:50, health:150, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Bone_Dragon_Animation.gif" },
    { name: "Ghost_Dragon", attack:19, defense:17, mindmg:25, maxdmg:50, health:200, speed:14, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Ghost_Dragon_Animation.gif" },

    { name: "Troglodyte", attack:4, defense:3, mindmg:1, maxdmg:3, health:5, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Troglodyte_Animation.gif" },
    { name: "Infernal_Troglodyte", attack:5, defense:4, mindmg:1, maxdmg:3, health:6, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Infernal_Troglodyte_Animation.gif" },
    { name: "Harpy", attack:6, defense:5, mindmg:1, maxdmg:4, health:14, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Harpy_Animation.gif" },
    { name: "Harpy_Hag", attack:6, defense:6, mindmg:1, maxdmg:4, health:14, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Harpy_Hag_Animation.gif" },
    { name: "Beholder", attack:9, defense:7, mindmg:3, maxdmg:5, health:22, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Beholder_Animation.gif" },
    { name: "Evil_Eye", attack:10, defense:8, mindmg:3, maxdmg:5, health:18, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Evil_Eye_Animation.gif" },
    { name: "Medusa", attack:9, defense:9, mindmg:6, maxdmg:8, health:25, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Medusa_Animation.gif" },
    { name: "Medusa_Queen", attack:10, defense:10, mindmg:6, maxdmg:8, health:30, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Medusa_Queen_Animation.gif" },
    { name: "Minotaur", attack:14, defense:12, mindmg:12, maxdmg:20, health:50, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Minotaur_Animation.gif" },
    { name: "Minotaur_King", attack:15, defense:15, mindmg:12, maxdmg:20, health:50, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Minotaur_King_Animation.gif" },
    { name: "Manticore", attack:15, defense:13, mindmg:14, maxdmg:20, health:80, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Manticore_Animation.gif" },
    { name: "Scorpicore", attack:16, defense:14, mindmg:14, maxdmg:20, health:80, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Scorpicore_Animation.gif" },
    { name: "Red_Dragon", attack:19, defense:19, mindmg:40, maxdmg:50, health:180, speed:11, type: "Lower Dragon", imgUrl:"css/img/creatures_animation/Creature_Red_Dragon_Animation.gif" },
    { name: "Black_Dragon", attack:25, defense:25, mindmg:40, maxdmg:50, health:300, speed:17, type: "High Dragon", imgUrl:"css/img/creatures_animation/Creature_Black_Dragon_Animation.gif" },

    { name: "Goblin", attack:4, defense:2, mindmg:1, maxdmg:2, health:5, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Goblin_Animation.gif" },
    { name: "Hobgoblin", attack:5, defense:3, mindmg:1, maxdmg:2, health:5, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Hobgoblin_Animation.gif" },
    { name: "Wolf_Rider", attack:7, defense:5, mindmg:2, maxdmg:4, health:10, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wolf_Rider_Animation.gif" },
    { name: "Wolf_Raider", attack:8, defense:5, mindmg:3, maxdmg:4, health:10, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wolf_Raider_Animation.gif" },
    { name: "Orc", attack:8, defense:4, mindmg:2, maxdmg:5, health:25, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Orc_Animation.gif"},
    { name: "Orc_Chieftain", attack:8, defense:4, mindmg:2, maxdmg:5, health:20, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Orc_Chieftain_Animation.gif" },
    { name: "Ogre", attack:13, defense:7, mindmg:6, maxdmg:12, health:40, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Ogre_Animation.gif" },
    { name: "Ogre_Mage", attack:13, defense:7, mindmg:6, maxdmg:12, health:60, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Ogre_Mage_Animation.gif" },
    { name: "Roc", attack:13, defense:11, mindmg:11, maxdmg:15, health:60, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Roc_Animation.gif" },
    { name: "Thunderbird", attack:13, defense:11, mindmg:11, maxdmg:15, health:60, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Thunderbird_Animation.gif" },
    { name: "Cyclops", attack:15, defense:12, mindmg:16, maxdmg:20, health:70, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Cyclops_Animation.gif" },
    { name: "Cyclops_King", attack:17, defense:13, mindmg:16, maxdmg:20, health:70, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Cyclops_King_Animation.gif" },
    { name: "Behemoth", attack:17, defense:17, mindmg:30, maxdmg:50, health:160, speed:6, type: "Lower Behemot", imgUrl:"css/img/creatures_animation/Creature_Behemoth_Animation.gif" },
    { name: "Ancient_Behemoth", attack:19, defense:19, mindmg:30, maxdmg:50, health:300, speed:9, type: "High Behemot", imgUrl:"css/img/creatures_animation/Creature_Ancient_Behemoth_Animation.gif" },

    { name: "Gnoll", attack:3, defense:5, mindmg:2, maxdmg:3, health:6, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Gnoll_Animation.gif" },
    { name: "Gnoll_Marauder", attack:4, defense:6, mindmg:2, maxdmg:3, health:6, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Gnoll_Marauder_Animation.gif" },
    { name: "Lizardman", attack:5, defense:6, mindmg:2, maxdmg:3, health:14, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Lizardman_Animation.gif" },
    { name: "Lizard_Warrior", attack:6, defense:8, mindmg:2, maxdmg:5, health:15, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Lizard_Warrior_Animation.gif" },
    { name: "Serpent_Fly", attack:7, defense:9, mindmg:2, maxdmg:5, health:20, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Serpent_Fly_Animation.gif" },
    { name: "Dragon_Fly", attack:8, defense:10, mindmg:2, maxdmg:5, health:20, speed:13, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Dragon_Fly_Animation.gif" },
    { name: "Basilisk", attack:11, defense:11, mindmg:6, maxdmg:10, health:35, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Basilisk_Animation.gif" },
    { name: "Greater_Basilisk", attack:12, defense:12, mindmg:6, maxdmg:10, health:40, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Greater_Basilisk_Animation.gif" },
    { name: "Gorgon", attack:10, defense:14, mindmg:12, maxdmg:16, health:70, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Gorgon_Animation.gif" },
    { name: "Mighty_Gorgon", attack:11, defense:16, mindmg:12, maxdmg:16, health:70, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Mighty_Gorgon_Animation.gif" },
    { name: "Wyvern", attack:14, defense:14, mindmg:14, maxdmg:18, health:70, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wyvern_Animation.gif" },
    { name: "Wyvern_Monarch", attack:14, defense:14, mindmg:18, maxdmg:22, health:70, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Wyvern_Monarch_Animation.gif" },
    { name: "Hydra", attack:16, defense:18, mindmg:25, maxdmg:45, health:175, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Hydra_Animation.gif" },
    { name: "Chaos_Hydra", attack:18, defense:20, mindmg:25, maxdmg:45, health:250, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Chaos_Hydra_Animation.gif" },

    { name: "Pixie", attack:2, defense:2, mindmg:1, maxdmg:2, health:3, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pixie_Animation.gif" },
    { name: "Sprite", attack:2, defense:2, mindmg:1, maxdmg:3, health:3, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Sprite_Animation.gif" },
    { name: "Air_Elemental", attack:9, defense:9, mindmg:2, maxdmg:8, health:25, speed:7, type: "Air", imgUrl:"css/img/creatures_animation/Creature_Air_Elemental_Animation.gif" },
    { name: "Storm_Elemental", attack:9, defense:9, mindmg:2, maxdmg:8, health:25, speed:8, type: "Air", imgUrl:"css/img/creatures_animation/Creature_Storm_Elemental_Animation.gif" },
    { name: "Water_Elemental", attack:8, defense:10, mindmg:3, maxdmg:7, health:30, speed:5, type: "Water", imgUrl:"css/img/creatures_animation/Creature_Water_Elemental_Animation.gif" },
    { name: "Ice_Elemental", attack:8, defense:10, mindmg:3, maxdmg:7, health:30, speed:6, type: "Water", imgUrl:"css/img/creatures_animation/Creature_Ice_Elemental_Animation.gif" },
    { name: "Fire_Elemental", attack:10, defense:8, mindmg:4, maxdmg:6, health:35, speed:6, type: "Fire", imgUrl:"css/img/creatures_animation/Creature_Fire_Elemental_Animation.gif" },
    { name: "Energy_Elemental", attack:12, defense:8, mindmg:4, maxdmg:6, health:35, speed:8, type: "Fire", imgUrl:"css/img/creatures_animation/Creature_Energy_Elemental_Animation.gif" },
    { name: "Earth_Elemental", attack:10, defense:10, mindmg:4, maxdmg:8, health:40, speed:4, type: "Earth", imgUrl:"css/img/creatures_animation/Creature_Earth_Elemental_Animation.gif" },
    { name: "Magma_Elemental", attack:11, defense:11, mindmg:6, maxdmg:10, health:40, speed:6, type: "Earth", imgUrl:"css/img/creatures_animation/Creature_Magma_Elemental_Animation.gif" },
    { name: "Psychic_Elemental", attack:15, defense:13, mindmg:10, maxdmg:20, health:75, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Psychic_Elemental_Animation.gif" },
    { name: "Magic_Elemental", attack:15, defense:13, mindmg:15, maxdmg:25, health:80, speed:9, type: "Magic Elemental", imgUrl:"css/img/creatures_animation/Creature_Magic_Elemental_Animation.gif" },
    { name: "Firebird", attack:18, defense:18, mindmg:30, maxdmg:40, health:150, speed:15, type: "Firebird", imgUrl:"css/img/creatures_animation/Creature_Firebird_Animation.gif" },
    { name: "Phoenix", attack:21, defense:18, mindmg:30, maxdmg:40, health:200, speed:21, type: "Phoenix", imgUrl:"css/img/creatures_animation/Creature_Phoenix_Animation.gif" },

    { name: "Nymph", attack:5, defense:2, mindmg:1, maxdmg:2, health:4, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Nymph_Animation.gif" },
    { name: "Oceanid", attack:6, defense:2, mindmg:1, maxdmg:3, health:4, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Oceanid_Animation.gif" },
    { name: "Crew_Mate", attack:7, defense:4, mindmg:2, maxdmg:4, health:15, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Crew_Mate_Animation.gif" },
    { name: "Seaman", attack:8, defense:6, mindmg:3, maxdmg:4, health:15, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Seaman_Animation.gif" },
    { name: "Pirate", attack:8, defense:6, mindmg:3, maxdmg:7, health:15, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pirate_Animation.gif" },
    { name: "Corsair", attack:10, defense:8, mindmg:3, maxdmg:7, health:15, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Corsair_Animation.gif" },
    { name: "Sea_Dog", attack:12, defense:11, mindmg:3, maxdmg:7, health:15, speed:8, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Sea_Dog_Animation.gif" },
    { name: "Stormbird", attack:10, defense:8, mindmg:6, maxdmg:9, health:30, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Stormbird_Animation.gif" },
    { name: "Ayssid", attack:11, defense:8, mindmg:6, maxdmg:10, health:30, speed:11, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Ayssid_Animation.gif" },
    { name: "Sea_Witch", attack:12, defense:7, mindmg:10, maxdmg:14, health:35, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Sea_Witch_Animation.gif" },
    { name: "Sorceress", attack:12, defense:9, mindmg:10, maxdmg:16, health:35, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Sorceress_Animation.gif" },
    { name: "Nix", attack:13, defense:16, mindmg:18, maxdmg:22, health:80, speed:6, type: "Nix", imgUrl:"css/img/creatures_animation/Creature_Nix_Animation.gif" },
    { name: "Nix_Warrior", attack:14, defense:17, mindmg:18, maxdmg:22, health:90, speed:15, type: "Nix Warrior", imgUrl:"css/img/creatures_animation/Creature_Nix_Warrior_Animation.gif" },
    { name: "Sea_Serpent", attack:22, defense:16, mindmg:30, maxdmg:55, health:180, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Sea_Serpent_Animation.gif" },
    { name: "Haspid", attack:29, defense:20, mindmg:30, maxdmg:55, health:300, speed:12, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Haspid_Animation.gif" },

    { name: "Peasant", attack:1, defense:1, mindmg:1, maxdmg:1, health:1, speed:3, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Peasant_Animation.gif" },
    { name: "Halfling", attack:4, defense:2, mindmg:1, maxdmg:3, health:4, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Halfling_Animation.gif" },
    { name: "Boar", attack:6, defense:5, mindmg:2, maxdmg:3, health:15, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Boar_Animation.gif" },
    { name: "Rogue", attack:8, defense:3, mindmg:2, maxdmg:4, health:10, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Rogue_Animation.gif" },
    { name: "Leprechaun", attack:8, defense:5, mindmg:3, maxdmg:5, health:15, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Leprechaun_Animation.gif" },
    { name: "Mummy", attack:7, defense:7, mindmg:3, maxdmg:5, health:30, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Mummy_Animation.gif" },
    { name: "Nomad", attack:9, defense:8, mindmg:2, maxdmg:6, health:30, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Nomad_Animation.gif" },
    { name: "Sharpshooter", attack:12, defense:10, mindmg:8, maxdmg:10, health:15, speed:9, type: "Sharpshooter", imgUrl:"css/img/creatures_animation/Creature_Sharpshooter_Animation.gif" },
    { name: "Satyr", attack:10, defense:11, mindmg:6, maxdmg:10, health:35, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Satyr_Animation.gif" },
    { name: "Steel_Golem", attack:10, defense:11, mindmg:6, maxdmg:8, health:45, speed:6, type: "Steel Golem", imgUrl:"css/img/creatures_animation/Creature_Steel_Golem_Animation.gif" },
    { name: "Troll", attack:14, defense:7, mindmg:10, maxdmg:15, health:40, speed:7, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Troll_Animation.gif" },
    { name: "Gold_Golem", attack:11, defense:12, mindmg:8, maxdmg:10, health:50, speed:5, type: "Gold Golem", imgUrl:"css/img/creatures_animation/Creature_Gold_Golem_Animation.gif" },
    { name: "Fangarm", attack:12, defense:12, mindmg:8, maxdmg:12, health:50, speed:6, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Fangarm_Animation.gif" },
    { name: "Diamond_Golem", attack:13, defense:12, mindmg:10, maxdmg:14, health:60, speed:5, type: "Diamond Golem", imgUrl:"css/img/creatures_animation/Creature_Diamond_Golem_Animation.gif" },
    { name: "Enchanter", attack:17, defense:12, mindmg:14, maxdmg:14, health:30, speed:9, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Enchanter_Animation.gif" },
    { name: "Faerie_Dragon", attack:20, defense:20, mindmg:20, maxdmg:30, health:500, speed:15, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Faerie_Dragon_Animation.gif" },
    { name: "Rust_Dragon", attack:30, defense:30, mindmg:50, maxdmg:50, health:750, speed:17, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Rust_Dragon_Animation.gif" },
    { name: "Crystal_Dragon", attack:40, defense:40, mindmg:60, maxdmg:75, health:800, speed:16, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Crystal_Dragon_Animation.gif" },
    { name: "Azure_Dragon", attack:50, defense:50, mindmg:70, maxdmg:80, health:1000, speed:19, type: "Lower Dragon", imgUrl:"css/img/creatures_animation/Creature_Azure_Dragon_Animation.gif" },
]
export const skill = [
  { name: "basic", value:0.05 },
  { name: "advanced", value:0.1 },
  { name: "expert", value:0.15 },
]
export const orb = [
  {name: "Orb Air", value:0.5},
  {name: "Orb Earth", value:0.5},
  {name: "Orb Fire", value:0.5},
  {name: "Orb Water", value:0.5},
]
// export const hero = [
//   {name: "Adelaide", value:"Frost Ring"},
//   {name: "Aislinn", value:"Meteor Shower"},
//   {name: "Alagar", value:"Ice Bolt"},
//   {name: "Ciele", value:"Magic Arrow"},
//   {name: "Deemer", value:"Meteor Shower"},
//   {name: "Luna", value:"Fire Wall"},
//   {name: "Manfred", value:"Fire Ball"},
//   {name: "Septienna", value:"Death Ripple"},
//   {name: "Solmyr", value:"Chain Lightning"},
//   {name: "Xarfax", value:"Fire Ball"},
//   {name: "Xyron", value:"Inferno"},
// ]
export const protections = [
  {name: "Protection Air", value: [0.5, 0.25], type: "air"},
  {name: "Protection Earth", value: [0.5, 0.25], type: "earth"},
  {name: "Protection Fire", value: [0.5, 0.25], type: "fire"},
  {name: "Protection Water", value: [0.5, 0.25], type: "water"},
]