
export const spells = [
    { name: "Magic Arrow", rate: 10, power: [10, 20, 30] },
    { name: "Fire Wall", rate: 10, power: [10, 20, 30] },
    { name: "Fire Ball", rate: 10, power: [15, 30, 60] },
    { name: "Land Mine", rate: 10, power: [25, 50, 100] },
    { name: "Armageddon", rate: 50, power: [30, 60, 120] },
    { name: "Inferno", rate: 10, power: [25, 50, 80] },
    { name: "Lightning Bolt", rate: 25, power: [10, 20, 30] },
    { name: "Chain Lightning", rate: 40, power: [25, 50, 100] },
    { name: "Ice Bolt", rate: 20, power: [10, 20, 30] },
    { name: "Frost Ring", rate: 10, power: [15, 30, 60] },
    { name: "Death Ripple", rate: 5, power: [10, 20, 30] },
    { name: "Meteor Shower", rate: 25, power: [25, 50, 100] },
    { name: "Implosion", rate: 75, power: [100, 200, 300] },
  ];
  export const creatures = [
    { name: "Pikeman", attack:4, defense:5, mindmg:1, maxdmg:3, health:10, speed:4, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Pikeman_Animation"},
    { name: "Halberdier", attack:6, defense:5, mindmg:2, maxdmg:3, health:10, speed:5, type: "normal", imgUrl:"css/img/creatures_animation/Creature_Halberdier_Animation" }, 
    { name: "Archer", attack:6, defense:3, mindmg:2, maxdmg:3, health:10, speed:4, type: "normal" },
    { name: "Marksman", attack:6, defense:5, mindmg:2, maxdmg:3, health:10, speed:6, type: "normal" },
    { name: "Griffin", attack:8, defense:8, mindmg:3, maxdmg:6, health:25, speed:6, type: "normal" },
    { name: "Royal Griffin", attack:9, defense:9, mindmg:3, maxdmg:6, health:25, speed:9, type: "normal" },
    { name: "Swordsman", attack:10, defense:12, mindmg:6, maxdmg:9, health:35, speed:5, type: "normal" },
    { name: "Crusader", attack:12, defense:12, mindmg:7, maxdmg:10, health:35, speed:6, type: "normal" },
    { name: "Monk", attack:12, defense:7, mindmg:10, maxdmg:12, health:30, speed:5, type: "normal" },
    { name: "Zealot", attack:12, defense:10, mindmg:10, maxdmg:12, health:30, speed:7, type: "normal" },
    { name: "Cavalier", attack:15, defense:15, mindmg:15, maxdmg:25, health:100, speed:7, type: "normal" },
    { name: "Champion", attack:16, defense:16, mindmg:20, maxdmg:25, health:100, speed:9, type: "normal" },
    { name: "Angel", attack:20, defense:20, mindmg:50, maxdmg:50, health:200, speed:12, type: "Hate Devil" },
    { name: "Archangel", attack:30, defense:30, mindmg:50, maxdmg:50, health:250, speed:18, type: "Hate Devil" },

    { name: "Centaur", attack:5, defense:3, mindmg:2, maxdmg:3, health:8, speed:6, type: "normal" },
    { name: "Centaur Captain", attack:6, defense:3, mindmg:2, maxdmg:3, health:10, speed:8, type: "normal" },
    { name: "Dwarf", attack:6, defense:7, mindmg:2, maxdmg:4, health:20, speed:3, type: "normal" },
    { name: "Battle Dwarf", attack:7, defense:7, mindmg:2, maxdmg:4, health:20, speed:5, type: "normal" },
    { name: "Wood Elf", attack:9, defense:5, mindmg:3, maxdmg:5, health:15, speed:6, type: "normal" },
    { name: "Grand Elf", attack:9, defense:5, mindmg:3, maxdmg:5, health:15, speed:7, type: "normal" },
    { name: "Pegasus", attack:9, defense:8, mindmg:5, maxdmg:9, health:30, speed:8, type: "normal" },
    { name: "Silver Pegasus", attack:9, defense:10, mindmg:5, maxdmg:9, health:30, speed:12, type: "normal" },
    { name: "Dendroid Guard", attack:9, defense:12, mindmg:10, maxdmg:14, health:55, speed:3, type: "normal" },
    { name: "Dendroid Soldier", attack:9, defense:12, mindmg:10, maxdmg:14, health:65, speed:4, type: "normal" },
    { name: "Unicorn", attack:15, defense:14, mindmg:18, maxdmg:22, health:90, speed:7, type: "normal" },
    { name: "War Unicorn", attack:15, defense:14, mindmg:18, maxdmg:22, health:110, speed:9, type: "normal" },
    { name: "Green Dragon", attack:18, defense:18, mindmg:40, maxdmg:50, health:180, speed:10, type: "lower dragon" },
    { name: "Gold Dragon", attack:27, defense:27, mindmg:40, maxdmg:50, health:250, speed:16, type: "mediom dragon" },

    { name: "Gremlin", attack:3, defense:3, mindmg:1, maxdmg:2, health:4, speed:4, type: "normal" },
    { name: "Master Gremlin", attack:4, defense:4, mindmg:1, maxdmg:2, health:4, speed:5, type: "normal" },
    { name: "Stone Gargoyle", attack:6, defense:6, mindmg:2, maxdmg:3, health:16, speed:6, type: "normal" },
    { name: "Obsidian Gargoyle", attack:7, defense:7, mindmg:2, maxdmg:3, health:16, speed:9, type: "normal" },
    { name: "Stone Golem", attack:7, defense:10, mindmg:4, maxdmg:5, health:30, speed:3, type: "Stone Golem" },
    { name: "Iron Golem", attack:9, defense:10, mindmg:4, maxdmg:5, health:35, speed:5, type: "Iron Golem" },
    { name: "Mage", attack:11, defense:8, mindmg:7, maxdmg:9, health:25, speed:5, type: "normal" },
    { name: "Arch Mage", attack:12, defense:9, mindmg:7, maxdmg:9, health:30, speed:7, type: "normal" },
    { name: "Genie", attack:12, defense:12, mindmg:13, maxdmg:16, health:40, speed:7, type: "normal" },
    { name: "Master Genie", attack:12, defense:12, mindmg:13, maxdmg:16, health:40, speed:11, type: "normal" },
    { name: "Naga", attack:16, defense:13, mindmg:20, maxdmg:20, health:110, speed:5, type: "normal" },
    { name: "Naga Queen", attack:16, defense:13, mindmg:30, maxdmg:30, health:110, speed:7, type: "normal" },
    { name: "Giant", attack:19, defense:16, mindmg:40, maxdmg:60, health:150, speed:7, type: "normal" },
    { name: "Titan", attack:24, defense:24, mindmg:40, maxdmg:60, health:300, speed:11, type: "Hate Black Dragon" },

    { name: "Imp", attack:2, defense:3, mindmg:1, maxdmg:2, health:4, speed:5, type: "normal" },
    { name: "Familiar", attack:4, defense:4, mindmg:1, maxdmg:2, health:4, speed:7, type: "normal" },
    { name: "Gog", attack:6, defense:4, mindmg:2, maxdmg:4, health:13, speed:4, type: "normal" },
    { name: "Magog", attack:7, defense:4, mindmg:2, maxdmg:4, health:13, speed:6, type: "normal" },
    { name: "Hell Hound", attack:10, defense:6, mindmg:2, maxdmg:7, health:25, speed:7, type: "normal" },
    { name: "Cerberus", attack:10, defense:8, mindmg:2, maxdmg:7, health:25, speed:8, type: "normal" },
    { name: "Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:35, speed:5, type: "normal" },
    { name: "Horned Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:40, speed:6, type: "normal" },
    { name: "Pit Fiend", attack:13, defense:13, mindmg:13, maxdmg:17, health:45, speed:6, type: "normal" },
    { name: "Pit Lord", attack:13, defense:113, mindmg:13, maxdmg:17, health:45, speed:7, type: "normal" },
    { name: "Efreet", attack:16, defense:12, mindmg:16, maxdmg:24, health:90, speed:9, type: "normal" },
    { name: "Efreet Sultan", attack:16, defense:14, mindmg:16, maxdmg:24, health:90, speed:13, type: "normal" },
    { name: "Devil", attack:19, defense:21, mindmg:30, maxdmg:40, health:160, speed:11, type: "normal" },
    { name: "Arch Devil", attack:26, defense:28, mindmg:30, maxdmg:40, health:200, speed:17, type: "normal" },

    { name: "Imp", attack:2, defense:3, mindmg:1, maxdmg:2, health:4, speed:5, type: "normal" },
    { name: "Familiar", attack:4, defense:4, mindmg:1, maxdmg:2, health:4, speed:7, type: "normal"},
    { name: "Gog", attack:6, defense:4, mindmg:2, maxdmg:4, health:13, speed:4, type: "normal" },
    { name: "Magog", attack:7, defense:4, mindmg:2, maxdmg:4, health:13, speed:6, type: "normal" },
    { name: "Hell Hound", attack:10, defense:6, mindmg:2, maxdmg:7, health:25, speed:7, type: "normal" },
    { name: "Cerberus", attack:10, defense:8, mindmg:2, maxdmg:7, health:25, speed:8, type: "normal" },
    { name: "Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:35, speed:5, type: "normal" },
    { name: "Horned Demon", attack:10, defense:10, mindmg:7, maxdmg:9, health:40, speed:6, type: "normal" },
    { name: "Pit Fiend", attack:13, defense:13, mindmg:13, maxdmg:17, health:45, speed:6, type: "normal" },
    { name: "Pit Lord", attack:13, defense:13, mindmg:13, maxdmg:17, health:45, speed:7, type: "normal" },
    { name: "Efreet", attack:16, defense:12, mindmg:16, maxdmg:24, health:90, speed:9, type: "normal" },
    { name: "Efreet Sultan", attack:16, defense:14, mindmg:16, maxdmg:24, health:90, speed:13, type: "normal" },
    { name: "Devil", attack:19, defense:21, mindmg:30, maxdmg:40, health:160, speed:11, type: "normal" },
    { name: "Arch Devil", attack:26, defense:28, mindmg:30, maxdmg:40, health:200, speed:17, type: "normal" },

    { name: "Skeleton", attack:5, defense:4, mindmg:1, maxdmg:3, health:6, speed:4, type: "normal" },
    { name: "Skeleton Warrior", attack:6, defense:6, mindmg:1, maxdmg:3, health:6, speed:5, type: "normal" },
    { name: "Walking Dead", attack:5, defense:5, mindmg:2, maxdmg:3, health:15, speed:3, type: "normal" },
    { name: "Zombie", attack:5, defense:5, mindmg:2, maxdmg:3, health:20, speed:4, type: "normal" },
    { name: "Wight", attack:7, defense:7, mindmg:3, maxdmg:5, health:18, speed:5, type: "normal" },
    { name: "Wraith", attack:7, defense:7, mindmg:3, maxdmg:5, health:18, speed:7, type: "normal" },
    { name: "Vampire", attack:10, defense:9, mindmg:5, maxdmg:8, health:30, speed:6, type: "normal" },
    { name: "Vampire Lord", attack:10, defense:10, mindmg:5, maxdmg:8, health:40, speed:9, type: "normal" },
    { name: "Lich", attack:13, defense:10, mindmg:11, maxdmg:13, health:30, speed:6, type: "normal" },
    { name: "Power Lich", attack:13, defense:10, mindmg:11, maxdmg:15, health:40, speed:7, type: "normal" },
    { name: "Black Knight", attack:16, defense:16, mindmg:15, maxdmg:30, health:120, speed:7, type: "normal" },
    { name: "Dread Knight", attack:18, defense:18, mindmg:15, maxdmg:30, health:120, speed:9, type: "normal" },
    { name: "Bone Dragon", attack:17, defense:15, mindmg:25, maxdmg:50, health:150, speed:9, type: "normal" },
    { name: "Ghost Dragon", attack:19, defense:17, mindmg:25, maxdmg:50, health:200, speed:14, type: "normal" },

    { name: "Troglodyte", attack:4, defense:3, mindmg:1, maxdmg:3, health:5, speed:4, type: "normal" },
    { name: "Infernal Troglodyte", attack:5, defense:4, mindmg:1, maxdmg:3, health:6, speed:5, type: "normal" },
    { name: "Harpy", attack:6, defense:5, mindmg:1, maxdmg:4, health:14, speed:6, type: "normal" },
    { name: "Harpy Hag", attack:6, defense:6, mindmg:1, maxdmg:4, health:14, speed:9, type: "normal" },
    { name: "Beholder", attack:9, defense:7, mindmg:3, maxdmg:5, health:22, speed:5, type: "normal" },
    { name: "Evil Eye", attack:10, defense:8, mindmg:3, maxdmg:5, health:18, speed:7, type: "normal" },
    { name: "Medusa", attack:9, defense:9, mindmg:6, maxdmg:8, health:25, speed:5, type: "normal" },
    { name: "Medusa Queen", attack:10, defense:10, mindmg:6, maxdmg:8, health:30, speed:6, type: "normal" },
    { name: "Minotaur", attack:14, defense:12, mindmg:12, maxdmg:20, health:50, speed:6, type: "normal" },
    { name: "Minotaur King", attack:15, defense:15, mindmg:12, maxdmg:20, health:50, speed:8, type: "normal" },
    { name: "Manticore", attack:15, defense:13, mindmg:14, maxdmg:20, health:80, speed:7, type: "normal" },
    { name: "Scorpicore", attack:16, defense:14, mindmg:14, maxdmg:20, health:80, speed:11, type: "normal" },
    { name: "Red Dragon", attack:19, defense:19, mindmg:40, maxdmg:50, health:180, speed:11, type: "Lower Dragon" },
    { name: "Black Dragon", attack:25, defense:25, mindmg:40, maxdmg:50, health:300, speed:17, type: "High Dragon" },

    { name: "Goblin", attack:4, defense:2, mindmg:1, maxdmg:2, health:5, speed:5, type: "normal" },
    { name: "Hobgoblin", attack:5, defense:3, mindmg:1, maxdmg:2, health:5, speed:7, type: "normal" },
    { name: "Wolf Rider", attack:7, defense:5, mindmg:2, maxdmg:4, health:10, speed:6, type: "normal" },
    { name: "Wolf Raider", attack:8, defense:5, mindmg:3, maxdmg:4, health:10, speed:8, type: "normal" },
    { name: "Orc", attack:8, defense:4, mindmg:2, maxdmg:5, health:25, speed:4, type: "normal"},
    { name: "Orc Chieftain", attack:8, defense:4, mindmg:2, maxdmg:5, health:20, speed:5, type: "normal" },
    { name: "Ogre", attack:13, defense:7, mindmg:6, maxdmg:12, health:40, speed:4, type: "normal" },
    { name: "Ogre Mage", attack:13, defense:7, mindmg:6, maxdmg:12, health:60, speed:5, type: "normal" },
    { name: "Roc", attack:13, defense:11, mindmg:11, maxdmg:15, health:60, speed:7, type: "normal" },
    { name: "Thunderbird", attack:13, defense:11, mindmg:11, maxdmg:15, health:60, speed:11, type: "normal" },
    { name: "Cyclops", attack:15, defense:12, mindmg:16, maxdmg:20, health:70, speed:6, type: "normal" },
    { name: "Cyclops King", attack:17, defense:13, mindmg:16, maxdmg:20, health:70, speed:8, type: "normal" },
    { name: "Behemoth", attack:17, defense:17, mindmg:30, maxdmg:50, health:160, speed:6, type: "Lower Behemot" },
    { name: "Ancient Behemoth", attack:19, defense:19, mindmg:30, maxdmg:50, health:300, speed:9, type: "High Behemot" },

    { name: "Gnoll", attack:3, defense:5, mindmg:2, maxdmg:3, health:6, speed:4, type: "normal" },
    { name: "Gnoll Marauder", attack:4, defense:6, mindmg:2, maxdmg:3, health:6, speed:5, type: "normal" },
    { name: "Lizardman", attack:5, defense:6, mindmg:2, maxdmg:3, health:14, speed:4, type: "normal" },
    { name: "Lizard Warrior", attack:6, defense:8, mindmg:2, maxdmg:5, health:15, speed:5, type: "normal" },
    { name: "Serpent Fly", attack:7, defense:9, mindmg:2, maxdmg:5, health:20, speed:9, type: "normal" },
    { name: "Dragon Fly", attack:8, defense:10, mindmg:2, maxdmg:5, health:20, speed:13, type: "normal" },
    { name: "Basilisk", attack:11, defense:11, mindmg:6, maxdmg:10, health:35, speed:5, type: "normal" },
    { name: "Greater Basilisk", attack:12, defense:12, mindmg:6, maxdmg:10, health:40, speed:7, type: "normal" },
    { name: "Gorgon", attack:10, defense:14, mindmg:12, maxdmg:16, health:70, speed:5, type: "normal" },
    { name: "Mighty Gorgon", attack:11, defense:16, mindmg:12, maxdmg:16, health:70, speed:6, type: "normal" },
    { name: "Wyvern", attack:14, defense:14, mindmg:14, maxdmg:18, health:70, speed:7, type: "normal" },
    { name: "Wyvern Monarch", attack:14, defense:14, mindmg:18, maxdmg:22, health:70, speed:11, type: "normal" },
    { name: "Hydra", attack:16, defense:18, mindmg:25, maxdmg:45, health:175, speed:5, type: "normal" },
    { name: "Chaos Hydra", attack:18, defense:20, mindmg:25, maxdmg:45, health:250, speed:7, type: "normal" },

    { name: "Pixie", attack:2, defense:2, mindmg:1, maxdmg:2, health:3, speed:7, type: "normal" },
    { name: "Sprite", attack:2, defense:2, mindmg:1, maxdmg:3, health:3, speed:9, type: "normal" },
    { name: "Air Elemental", attack:9, defense:9, mindmg:2, maxdmg:8, health:25, speed:7, type: "Air" },
    { name: "Storm Elemental", attack:9, defense:9, mindmg:2, maxdmg:8, health:25, speed:8, type: "Air" },
    { name: "Water Elemental", attack:8, defense:10, mindmg:3, maxdmg:7, health:30, speed:5, type: "Water" },
    { name: "Ice Elemental", attack:8, defense:10, mindmg:3, maxdmg:7, health:30, speed:6, type: "Water" },
    { name: "Fire Elemental", attack:10, defense:8, mindmg:4, maxdmg:6, health:35, speed:6, type: "Fire" },
    { name: "Energy Elemental", attack:12, defense:8, mindmg:4, maxdmg:6, health:35, speed:8, type: "Fire" },
    { name: "Earth Elemental", attack:10, defense:10, mindmg:4, maxdmg:8, health:40, speed:4, type: "Earth" },
    { name: "Magma Elemental", attack:11, defense:11, mindmg:6, maxdmg:10, health:40, speed:6, type: "Earth" },
    { name: "Psychic Elemental", attack:15, defense:13, mindmg:10, maxdmg:20, health:75, speed:7, type: "normal" },
    { name: "Magic Elemental", attack:15, defense:13, mindmg:15, maxdmg:25, health:80, speed:9, type: "Magic Elemental" },
    { name: "Firebird", attack:18, defense:18, mindmg:30, maxdmg:40, health:150, speed:15, type: "Firebird" },
    { name: "Phoenix", attack:21, defense:18, mindmg:30, maxdmg:40, health:200, speed:21, type: "Phoenix" },

    { name: "Nymph", attack:5, defense:2, mindmg:1, maxdmg:2, health:4, speed:6, type: "normal" },
    { name: "Oceanid", attack:6, defense:2, mindmg:1, maxdmg:3, health:4, speed:8, type: "normal" },
    { name: "Crew Mate", attack:7, defense:4, mindmg:2, maxdmg:4, health:15, speed:5, type: "normal" },
    { name: "Seaman", attack:8, defense:6, mindmg:3, maxdmg:4, health:15, speed:6, type: "normal" },
    { name: "Pirate", attack:8, defense:6, mindmg:3, maxdmg:7, health:15, speed:5, type: "normal" },
    { name: "Corsair", attack:10, defense:8, mindmg:3, maxdmg:7, health:15, speed:7, type: "normal" },
    { name: "Sea Dog", attack:12, defense:11, mindmg:3, maxdmg:7, health:15, speed:8, type: "normal" },
    { name: "Stormbird", attack:10, defense:8, mindmg:6, maxdmg:9, health:30, speed:9, type: "normal" },
    { name: "Ayssid", attack:11, defense:8, mindmg:6, maxdmg:10, health:30, speed:11, type: "normal" },
    { name: "Sea Witch", attack:12, defense:7, mindmg:10, maxdmg:14, health:35, speed:6, type: "normal" },
    { name: "Sorceress", attack:12, defense:9, mindmg:10, maxdmg:16, health:35, speed:7, type: "normal" },
    { name: "Nix", attack:13, defense:16, mindmg:18, maxdmg:22, health:80, speed:6, type: "Nix" },
    { name: "Nix Warrior", attack:14, defense:17, mindmg:18, maxdmg:22, health:90, speed:15, type: "Nix Warrior" },
    { name: "Sea Serpent", attack:22, defense:16, mindmg:30, maxdmg:55, health:180, speed:9, type: "normal" },
    { name: "Haspid", attack:29, defense:20, mindmg:30, maxdmg:55, health:300, speed:12, type: "normal" },

    { name: "Peasant", attack:1, defense:1, mindmg:1, maxdmg:1, health:1, speed:3, type: "normal" },
    { name: "Halfling", attack:4, defense:2, mindmg:1, maxdmg:3, health:4, speed:5, type: "normal" },
    { name: "Boar", attack:6, defense:5, mindmg:2, maxdmg:3, health:15, speed:6, type: "normal" },
    { name: "Rogue", attack:8, defense:3, mindmg:2, maxdmg:4, health:10, speed:6, type: "normal" },
    { name: "Leprechaun", attack:8, defense:5, mindmg:3, maxdmg:5, health:15, speed:5, type: "normal" },
    { name: "Mummy", attack:7, defense:7, mindmg:3, maxdmg:5, health:30, speed:5, type: "normal" },
    { name: "Nomad", attack:9, defense:8, mindmg:2, maxdmg:6, health:30, speed:7, type: "normal" },
    { name: "Sharpshooter", attack:12, defense:10, mindmg:8, maxdmg:10, health:15, speed:9, type: "Sharpshooter" },
    { name: "Satyr", attack:10, defense:11, mindmg:6, maxdmg:10, health:35, speed:7, type: "normal" },
    { name: "Steel Golem", attack:10, defense:11, mindmg:6, maxdmg:8, health:45, speed:6, type: "Steel Golem" },
    { name: "Troll", attack:14, defense:7, mindmg:10, maxdmg:15, health:40, speed:7, type: "normal" },
    { name: "Gold Golem", attack:11, defense:12, mindmg:8, maxdmg:10, health:50, speed:5, type: "Gold Golem" },
    { name: "Fangarm", attack:12, defense:12, mindmg:8, maxdmg:12, health:50, speed:6, type: "normal" },
    { name: "Diamond Golem", attack:13, defense:12, mindmg:10, maxdmg:14, health:60, speed:5, type: "Diamond Golem" },
    { name: "Enchanter", attack:17, defense:12, mindmg:14, maxdmg:14, health:30, speed:9, type: "normal" },
    { name: "Faerie Dragon", attack:20, defense:20, mindmg:20, maxdmg:30, health:500, speed:15, type: "normal" },
    { name: "Rust Dragon", attack:30, defense:30, mindmg:50, maxdmg:50, health:750, speed:17, type: "normal" },
    { name: "Crystal Dragon", attack:40, defense:40, mindmg:60, maxdmg:75, health:800, speed:16, type: "normal" },
    { name: "Azure Dragon", attack:50, defense:50, mindmg:70, maxdmg:80, health:1000, speed:19, type: "Lower Dragon" },



]